# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: istheweb.shop::lang.option.label

# Model Form Field configuration
form: $/istheweb/shop/models/option/fields.yaml

# Model Class name
modelClass: Istheweb\Shop\Models\Option

# Default redirect location
defaultRedirect: istheweb/shop/options

# Create page
create:
    title: istheweb.shop::lang.option.create_title
    redirect: istheweb/shop/options/update/:id
    redirectClose: istheweb/shop/options

# Update page
update:
    title: istheweb.shop::lang.option.update_title
    redirect: istheweb/shop/options
    redirectClose: istheweb/shop/options

# Preview page
preview:
    title: istheweb.shop::lang.option.preview_title