values:
    label: istheweb.shop::lang.options.menu_label
    manage:
        form: $/istheweb/shop/models/optionvalue/fields.yaml
        list: $/istheweb/shop/models/optionvalue/columns.yaml
    view:
        list: $/istheweb/shop/models/optionvalue/columns.yaml
        toolbarButtons: create|delete
    deferredBinding: true