countries:
    label: istheweb.shop::lang.fields.countries
    view:
        list: ~/plugins/rainlab/location/models/country/columns.yaml
        toolbarButtons: add|remove
    manage:
        showSearch: true
        recordsPerPage: 10
        list: ~/plugins/rainlab/location/models/country/columns.yaml
        form: ~/plugins/rainlab/location/models/country/fields.yaml
states:
    label: istheweb.shop::lang.fields.states
    view:
        list: ~/plugins/rainlab/location/models/state/columns.yaml
        toolbarButtons: add|remove
    manage:
        showSearch: true
        recordsPerPage: 10
        list: ~/plugins/rainlab/location/models/state/columns.yaml
        form: ~/plugins/rainlab/location/models/state/fields.yaml