customer:
    label: istheweb.shop::lang.customer.label
    view:
        form: $/istheweb/shop/models/customer/fields.yaml
        toolbarButtons: create|link|unlink
    manage:
        form: $/istheweb/shop/models/customer/fields.yaml
        list: $/istheweb/shop/models/customer/columns.yaml
        showSearch: true
        context: create
order_items:
    label: istheweb.shop::lang.order_items.menu_label
    manage:
        form: $/istheweb/shop/models/orderitem/fields.yaml
        list: $/istheweb/shop/models/orderitem/columns.yaml
    view:
        list: $/istheweb/shop/models/orderitem/columns.yaml
        toolbarButtons: create|delete

shipping_address:
    label: istheweb.shop::lang.fields.shipping_address
    view:
        form: $/istheweb/shop/models/address/fields.yaml
        toolbarButtons: create|link|unlink
    manage:
        form: $/istheweb/shop/models/address/fields.yaml
        list: $/istheweb/shop/models/address/columns.yaml
        showSearch: true
        scope: findByCustomer
billing_address:
    label: istheweb.shop::lang.fields.billing_address
    view:
        form: $/istheweb/shop/models/address/fields.yaml
        toolbarButtons: create|link|unlink
    manage:
        form: $/istheweb/shop/models/address/fields.yaml
        list: $/istheweb/shop/models/address/columns.yaml
        showSearch: true
        scope: findByCustomer
shipment:
    label: istheweb.shop::lang.fields.shipment
    view:
        form: $/istheweb/shop/models/shipment/fields.yaml
        toolbarButtons: update|delete
    manage:
        form: $/istheweb/shop/models/shipment/fields.yaml
        list: $/istheweb/shop/models/shipment/columns.yaml