# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: istheweb.shop::lang.order.label

# Model Form Field configuration
form: $/istheweb/shop/models/order/fields.yaml

# Model Class name
modelClass: Istheweb\Shop\Models\Order

# Default redirect location
defaultRedirect: istheweb/shop/orders

# Create page
create:
    title: istheweb.shop::lang.order.create_title
    redirect: istheweb/shop/orders/update/:id
    redirectClose: istheweb/shop/orders

# Update page
update:
    title: istheweb.shop::lang.order.update_title
    redirect: istheweb/shop/orders
    redirectClose: istheweb/shop/orders

# Preview page
preview:
    title: istheweb.shop::lang.order.preview_title